# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.Agent import Agent
from org.eclipse.lyo.oslc.domains.cm.ChangeRequest import ChangeRequest
from org.eclipse.lyo.oslc.domains.config.ChangeSet import ChangeSet
from org.eclipse.lyo.oslc.domains.cm.Defect import Defect
from org.eclipse.lyo.oslc4j.core.model.Discussion import Discussion
from org.eclipse.lyo.oslc.domains.Person import Person
from org.eclipse.lyo.oslc.domains.cm.Priority import Priority
from org.eclipse.lyo.oslc.domains.rm.Requirement import Requirement
from org.eclipse.lyo.oslc.domains.cm.State import State
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_CM)
@oslc_name("Task")
@oslc_resource_shape(describes=NS_OSLC_CM["Task"], title="Task Shape")
class Task(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:short_title
        # End of user code
        self._short_title = None
        # Start of user code attributeAnnotation:description
        # End of user code
        self._description = None
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:identifier
        # End of user code
        self._identifier = None
        # Start of user code attributeAnnotation:subject
        # End of user code
        self._subject = set()
        # Start of user code attributeAnnotation:creator
        # End of user code
        self._creator = set()
        # Start of user code attributeAnnotation:contributor
        # End of user code
        self._contributor = set()
        # Start of user code attributeAnnotation:created
        # End of user code
        self._created = None
        # Start of user code attributeAnnotation:modified
        # End of user code
        self._modified = None
        # Start of user code attributeAnnotation:service_provider
        # End of user code
        self._service_provider = set()
        # Start of user code attributeAnnotation:instance_shape
        # End of user code
        self._instance_shape = set()
        # Start of user code attributeAnnotation:discussed_by
        # End of user code
        self._discussed_by = None
        # Start of user code attributeAnnotation:close_date
        # End of user code
        self._close_date = None
        # Start of user code attributeAnnotation:status
        # End of user code
        self._status = None
        # Start of user code attributeAnnotation:closed
        # End of user code
        self._closed = None
        # Start of user code attributeAnnotation:in_progress
        # End of user code
        self._in_progress = None
        # Start of user code attributeAnnotation:fixed
        # End of user code
        self._fixed = None
        # Start of user code attributeAnnotation:approved
        # End of user code
        self._approved = None
        # Start of user code attributeAnnotation:reviewed
        # End of user code
        self._reviewed = None
        # Start of user code attributeAnnotation:verified
        # End of user code
        self._verified = None
        # Start of user code attributeAnnotation:related_change_request
        # End of user code
        self._related_change_request = set()
        # Start of user code attributeAnnotation:affects_plan_item
        # End of user code
        self._affects_plan_item = set()
        # Start of user code attributeAnnotation:affected_by_defect
        # End of user code
        self._affected_by_defect = set()
        # Start of user code attributeAnnotation:tracks_requirement
        # End of user code
        self._tracks_requirement = set()
        # Start of user code attributeAnnotation:implements_requirement
        # End of user code
        self._implements_requirement = set()
        # Start of user code attributeAnnotation:affects_requirement
        # End of user code
        self._affects_requirement = set()
        # Start of user code attributeAnnotation:tracks_change_set
        # End of user code
        self._tracks_change_set = set()
        # Start of user code attributeAnnotation:parent
        # End of user code
        self._parent = set()
        # Start of user code attributeAnnotation:priority
        # End of user code
        self._priority = set()
        # Start of user code attributeAnnotation:state
        # End of user code
        self._state = None
        # Start of user code attributeAnnotation:authorizer
        # End of user code
        self._authorizer = set()
        
        @property
        # Start of user code getterAnnotation:short_title
        # End of user code
        @oslc_name("shortTitle")
        @oslc_property_definition(oslc_constants.NS_OSLC["shortTitle"])
        @oslc_description("Shorter form of dcterms:title for the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def short_title(self):
            # Start of user code getterInit:short_title
            # End of user code
            return self._short_title
    
        @short_title.setter
        def short_title(self, value: str):
            # Start of user code setterInit:short_title
            # End of user code
            self._short_title = value
            # Start of user code setterFinalize:short_title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:description
        # End of user code
        @oslc_name("description")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["description"])
        @oslc_description("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def description(self):
            # Start of user code getterInit:description
            # End of user code
            return self._description
    
        @description.setter
        def description(self, value: str):
            # Start of user code setterInit:description
            # End of user code
            self._description = value
            # Start of user code setterFinalize:description
            # End of user code
    
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:identifier
        # End of user code
        @oslc_name("identifier")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["identifier"])
        @oslc_description("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def identifier(self):
            # Start of user code getterInit:identifier
            # End of user code
            return self._identifier
    
        @identifier.setter
        def identifier(self, value: str):
            # Start of user code setterInit:identifier
            # End of user code
            self._identifier = value
            # Start of user code setterFinalize:identifier
            # End of user code
    
        @property
        # Start of user code getterAnnotation:subject
        # End of user code
        @oslc_name("subject")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["subject"])
        @oslc_description("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def subject(self):
            # Start of user code getterInit:subject
            # End of user code
            return self._subject
    
        @subject.setter
        def subject(self, value: Set[str]):
            # Start of user code setterInit:subject
            # End of user code
            self._subject = value
            # Start of user code setterFinalize:subject
            # End of user code
    
        @property
        # Start of user code getterAnnotation:creator
        # End of user code
        @oslc_name("creator")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["creator"])
        @oslc_description("Creator or creators of the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def creator(self):
            # Start of user code getterInit:creator
            # End of user code
            return self._creator
    
        @creator.setter
        def creator(self, value: Set[Link]):
            # Start of user code setterInit:creator
            # End of user code
            self._creator = value
            # Start of user code setterFinalize:creator
            # End of user code
    
        @property
        # Start of user code getterAnnotation:contributor
        # End of user code
        @oslc_name("contributor")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["contributor"])
        @oslc_description("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def contributor(self):
            # Start of user code getterInit:contributor
            # End of user code
            return self._contributor
    
        @contributor.setter
        def contributor(self, value: Set[Link]):
            # Start of user code setterInit:contributor
            # End of user code
            self._contributor = value
            # Start of user code setterFinalize:contributor
            # End of user code
    
        @property
        # Start of user code getterAnnotation:created
        # End of user code
        @oslc_name("created")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["created"])
        @oslc_description("Timestamp of resource creation")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def created(self):
            # Start of user code getterInit:created
            # End of user code
            return self._created
    
        @created.setter
        def created(self, value: datetime):
            # Start of user code setterInit:created
            # End of user code
            self._created = value
            # Start of user code setterFinalize:created
            # End of user code
    
        @property
        # Start of user code getterAnnotation:modified
        # End of user code
        @oslc_name("modified")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["modified"])
        @oslc_description("Timestamp of latest resource modification")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def modified(self):
            # Start of user code getterInit:modified
            # End of user code
            return self._modified
    
        @modified.setter
        def modified(self, value: datetime):
            # Start of user code setterInit:modified
            # End of user code
            self._modified = value
            # Start of user code setterFinalize:modified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:service_provider
        # End of user code
        @oslc_name("serviceProvider")
        @oslc_property_definition(oslc_constants.NS_OSLC["serviceProvider"])
        @oslc_description("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def service_provider(self):
            # Start of user code getterInit:service_provider
            # End of user code
            return self._service_provider
    
        @service_provider.setter
        def service_provider(self, value: Set[Link]):
            # Start of user code setterInit:service_provider
            # End of user code
            self._service_provider = value
            # Start of user code setterFinalize:service_provider
            # End of user code
    
        @property
        # Start of user code getterAnnotation:instance_shape
        # End of user code
        @oslc_name("instanceShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["instanceShape"])
        @oslc_description("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def instance_shape(self):
            # Start of user code getterInit:instance_shape
            # End of user code
            return self._instance_shape
    
        @instance_shape.setter
        def instance_shape(self, value: Set[Link]):
            # Start of user code setterInit:instance_shape
            # End of user code
            self._instance_shape = value
            # Start of user code setterFinalize:instance_shape
            # End of user code
    
        @property
        # Start of user code getterAnnotation:discussed_by
        # End of user code
        @oslc_name("discussedBy")
        @oslc_property_definition(oslc_constants.NS_OSLC["discussedBy"])
        @oslc_description("A series of notes and comments about this resource.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_constants[DISCUSSION_TYPE])
        @oslc_read_only(False)
        def discussed_by(self):
            # Start of user code getterInit:discussed_by
            # End of user code
            return self._discussed_by
    
        @discussed_by.setter
        def discussed_by(self, value: Link):
            # Start of user code setterInit:discussed_by
            # End of user code
            self._discussed_by = value
            # Start of user code setterFinalize:discussed_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:close_date
        # End of user code
        @oslc_name("closeDate")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["closeDate"])
        @oslc_description("The date at which no further activity or work is intended to be conducted.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def close_date(self):
            # Start of user code getterInit:close_date
            # End of user code
            return self._close_date
    
        @close_date.setter
        def close_date(self, value: datetime):
            # Start of user code setterInit:close_date
            # End of user code
            self._close_date = value
            # Start of user code setterFinalize:close_date
            # End of user code
    
        @property
        # Start of user code getterAnnotation:status
        # End of user code
        @oslc_name("status")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["status"])
        @oslc_description("Used to indicate the status of the change request based on values defined by the service provider. Most often a read-only property. Some possible values may include: 'Submitted', 'Done', 'InProgress', etc.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def status(self):
            # Start of user code getterInit:status
            # End of user code
            return self._status
    
        @status.setter
        def status(self, value: str):
            # Start of user code setterInit:status
            # End of user code
            self._status = value
            # Start of user code setterFinalize:status
            # End of user code
    
        @property
        # Start of user code getterAnnotation:closed
        # End of user code
        @oslc_name("closed")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["closed"])
        @oslc_description("Whether or not the Change Request is completely done, no further fixes or fix verification is needed.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def closed(self):
            # Start of user code getterInit:closed
            # End of user code
            return self._closed
    
        @closed.setter
        def closed(self, value: bool):
            # Start of user code setterInit:closed
            # End of user code
            self._closed = value
            # Start of user code setterFinalize:closed
            # End of user code
    
        @property
        # Start of user code getterAnnotation:in_progress
        # End of user code
        @oslc_name("inProgress")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["inProgress"])
        @oslc_description("Whether or not the Change Request in a state indicating that active work is occurring. If oslc_cm:inprogress is true, then oslc_cm:fixed and oslc_cm:closed must also be false")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def in_progress(self):
            # Start of user code getterInit:in_progress
            # End of user code
            return self._in_progress
    
        @in_progress.setter
        def in_progress(self, value: bool):
            # Start of user code setterInit:in_progress
            # End of user code
            self._in_progress = value
            # Start of user code setterFinalize:in_progress
            # End of user code
    
        @property
        # Start of user code getterAnnotation:fixed
        # End of user code
        @oslc_name("fixed")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["fixed"])
        @oslc_description("Whether or not the Change Request has been fixed.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def fixed(self):
            # Start of user code getterInit:fixed
            # End of user code
            return self._fixed
    
        @fixed.setter
        def fixed(self, value: bool):
            # Start of user code setterInit:fixed
            # End of user code
            self._fixed = value
            # Start of user code setterFinalize:fixed
            # End of user code
    
        @property
        # Start of user code getterAnnotation:approved
        # End of user code
        @oslc_name("approved")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["approved"])
        @oslc_description("Whether or not the Change Request has been approved.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def approved(self):
            # Start of user code getterInit:approved
            # End of user code
            return self._approved
    
        @approved.setter
        def approved(self, value: bool):
            # Start of user code setterInit:approved
            # End of user code
            self._approved = value
            # Start of user code setterFinalize:approved
            # End of user code
    
        @property
        # Start of user code getterAnnotation:reviewed
        # End of user code
        @oslc_name("reviewed")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["reviewed"])
        @oslc_description("Whether or not the Change Request has been reviewed.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def reviewed(self):
            # Start of user code getterInit:reviewed
            # End of user code
            return self._reviewed
    
        @reviewed.setter
        def reviewed(self, value: bool):
            # Start of user code setterInit:reviewed
            # End of user code
            self._reviewed = value
            # Start of user code setterFinalize:reviewed
            # End of user code
    
        @property
        # Start of user code getterAnnotation:verified
        # End of user code
        @oslc_name("verified")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["verified"])
        @oslc_description("Whether or not the resolution or fix of the Change Request has been verified.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def verified(self):
            # Start of user code getterInit:verified
            # End of user code
            return self._verified
    
        @verified.setter
        def verified(self, value: bool):
            # Start of user code setterInit:verified
            # End of user code
            self._verified = value
            # Start of user code setterFinalize:verified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:related_change_request
        # End of user code
        @oslc_name("relatedChangeRequest")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["relatedChangeRequest"])
        @oslc_description("This relationship is loosely coupled and has no specific meaning. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def related_change_request(self):
            # Start of user code getterInit:related_change_request
            # End of user code
            return self._related_change_request
    
        @related_change_request.setter
        def related_change_request(self, value: Set[Link]):
            # Start of user code setterInit:related_change_request
            # End of user code
            self._related_change_request = value
            # Start of user code setterFinalize:related_change_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:affects_plan_item
        # End of user code
        @oslc_name("affectsPlanItem")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["affectsPlanItem"])
        @oslc_description("Change request affects a plan item. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def affects_plan_item(self):
            # Start of user code getterInit:affects_plan_item
            # End of user code
            return self._affects_plan_item
    
        @affects_plan_item.setter
        def affects_plan_item(self, value: Set[Link]):
            # Start of user code setterInit:affects_plan_item
            # End of user code
            self._affects_plan_item = value
            # Start of user code setterFinalize:affects_plan_item
            # End of user code
    
        @property
        # Start of user code getterAnnotation:affected_by_defect
        # End of user code
        @oslc_name("affectedByDefect")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["affectedByDefect"])
        @oslc_description("Change request is affected by a reported defect. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[DEFECT_TYPE])
        @oslc_read_only(False)
        def affected_by_defect(self):
            # Start of user code getterInit:affected_by_defect
            # End of user code
            return self._affected_by_defect
    
        @affected_by_defect.setter
        def affected_by_defect(self, value: Set[Link]):
            # Start of user code setterInit:affected_by_defect
            # End of user code
            self._affected_by_defect = value
            # Start of user code setterFinalize:affected_by_defect
            # End of user code
    
        @property
        # Start of user code getterAnnotation:tracks_requirement
        # End of user code
        @oslc_name("tracksRequirement")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["tracksRequirement"])
        @oslc_description("Tracks the associated Requirement or Requirement ChangeSet resources. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_rm_constants[REQUIREMENT_TYPE])
        @oslc_read_only(False)
        def tracks_requirement(self):
            # Start of user code getterInit:tracks_requirement
            # End of user code
            return self._tracks_requirement
    
        @tracks_requirement.setter
        def tracks_requirement(self, value: Set[Link]):
            # Start of user code setterInit:tracks_requirement
            # End of user code
            self._tracks_requirement = value
            # Start of user code setterFinalize:tracks_requirement
            # End of user code
    
        @property
        # Start of user code getterAnnotation:implements_requirement
        # End of user code
        @oslc_name("implementsRequirement")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["implementsRequirement"])
        @oslc_description("Implements associated Requirement. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_rm_constants[REQUIREMENT_TYPE])
        @oslc_read_only(False)
        def implements_requirement(self):
            # Start of user code getterInit:implements_requirement
            # End of user code
            return self._implements_requirement
    
        @implements_requirement.setter
        def implements_requirement(self, value: Set[Link]):
            # Start of user code setterInit:implements_requirement
            # End of user code
            self._implements_requirement = value
            # Start of user code setterFinalize:implements_requirement
            # End of user code
    
        @property
        # Start of user code getterAnnotation:affects_requirement
        # End of user code
        @oslc_name("affectsRequirement")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["affectsRequirement"])
        @oslc_description("Change request affecting a Requirement. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_rm_constants[REQUIREMENT_TYPE])
        @oslc_read_only(False)
        def affects_requirement(self):
            # Start of user code getterInit:affects_requirement
            # End of user code
            return self._affects_requirement
    
        @affects_requirement.setter
        def affects_requirement(self, value: Set[Link]):
            # Start of user code setterInit:affects_requirement
            # End of user code
            self._affects_requirement = value
            # Start of user code setterFinalize:affects_requirement
            # End of user code
    
        @property
        # Start of user code getterAnnotation:tracks_change_set
        # End of user code
        @oslc_name("tracksChangeSet")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["tracksChangeSet"])
        @oslc_description("Tracks SCM change set resource. It is likely that the target resource will be an oslc_scm:ChangeSet but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_config_constants[CHANGESET_TYPE])
        @oslc_read_only(False)
        def tracks_change_set(self):
            # Start of user code getterInit:tracks_change_set
            # End of user code
            return self._tracks_change_set
    
        @tracks_change_set.setter
        def tracks_change_set(self, value: Set[Link]):
            # Start of user code setterInit:tracks_change_set
            # End of user code
            self._tracks_change_set = value
            # Start of user code setterFinalize:tracks_change_set
            # End of user code
    
        @property
        # Start of user code getterAnnotation:parent
        # End of user code
        @oslc_name("parent")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["parent"])
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[CHANGEREQUEST_TYPE])
        @oslc_read_only(False)
        def parent(self):
            # Start of user code getterInit:parent
            # End of user code
            return self._parent
    
        @parent.setter
        def parent(self, value: Set[Link]):
            # Start of user code setterInit:parent
            # End of user code
            self._parent = value
            # Start of user code setterFinalize:parent
            # End of user code
    
        @property
        # Start of user code getterAnnotation:priority
        # End of user code
        @oslc_name("priority")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["priority"])
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[PRIORITY_TYPE])
        @oslc_read_only(False)
        def priority(self):
            # Start of user code getterInit:priority
            # End of user code
            return self._priority
    
        @priority.setter
        def priority(self, value: Set[Link]):
            # Start of user code setterInit:priority
            # End of user code
            self._priority = value
            # Start of user code setterFinalize:priority
            # End of user code
    
        @property
        # Start of user code getterAnnotation:state
        # End of user code
        @oslc_name("state")
        @oslc_property_definition(oslc_cm_vocabulary_constants.NS_OSLC_CM["state"])
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[STATE_TYPE])
        @oslc_read_only(False)
        def state(self):
            # Start of user code getterInit:state
            # End of user code
            return self._state
    
        @state.setter
        def state(self, value: Link):
            # Start of user code setterInit:state
            # End of user code
            self._state = value
            # Start of user code setterFinalize:state
            # End of user code
    
        @property
        # Start of user code getterAnnotation:authorizer
        # End of user code
        @oslc_name("authorizer")
        @oslc_property_definition(oslc_cm_constants.NS_OSLC_CM["authorizer"])
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[AGENT_TYPE])
        @oslc_read_only(False)
        def authorizer(self):
            # Start of user code getterInit:authorizer
            # End of user code
            return self._authorizer
    
        @authorizer.setter
        def authorizer(self, value: Set[Link]):
            # Start of user code setterInit:authorizer
            # End of user code
            self._authorizer = value
            # Start of user code setterFinalize:authorizer
            # End of user code
    
    
