# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.dcterms_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.foaf_constants import NS_FOAF
from org.eclipse.lyo.oslc4j.core.model.oslc_constants import NS_OSLC
from org.eclipse.lyo.oslc.domains.rm.oslc_rm_constants import NS_OSLC_RM
from org.eclipse.lyo.oslc.domains.dcterms_vocabulary_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.oslc_rm_vocabulary_constants import NS_OSLC_RM
from org.eclipse.lyo.oslc.domains.Person import Person
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_RM)
@oslc_name("Requirement")
@oslc_resource_shape(describes=NS_OSLC_RM["Requirement"], title="Requirement Shape")
class Requirement(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:description
        # End of user code
        self._description = None
        # Start of user code attributeAnnotation:identifier
        # End of user code
        self._identifier = None
        # Start of user code attributeAnnotation:short_title
        # End of user code
        self._short_title = None
        # Start of user code attributeAnnotation:subject
        # End of user code
        self._subject = set()
        # Start of user code attributeAnnotation:creator
        # End of user code
        self._creator = set()
        # Start of user code attributeAnnotation:contributor
        # End of user code
        self._contributor = set()
        # Start of user code attributeAnnotation:created
        # End of user code
        self._created = None
        # Start of user code attributeAnnotation:modified
        # End of user code
        self._modified = None
        # Start of user code attributeAnnotation:service_provider
        # End of user code
        self._service_provider = set()
        # Start of user code attributeAnnotation:instance_shape
        # End of user code
        self._instance_shape = set()
        # Start of user code attributeAnnotation:elaborated_by
        # End of user code
        self._elaborated_by = set()
        # Start of user code attributeAnnotation:elaborates
        # End of user code
        self._elaborates = set()
        # Start of user code attributeAnnotation:specified_by
        # End of user code
        self._specified_by = set()
        # Start of user code attributeAnnotation:specifies
        # End of user code
        self._specifies = set()
        # Start of user code attributeAnnotation:affected_by
        # End of user code
        self._affected_by = set()
        # Start of user code attributeAnnotation:tracked_by
        # End of user code
        self._tracked_by = set()
        # Start of user code attributeAnnotation:implemented_by
        # End of user code
        self._implemented_by = set()
        # Start of user code attributeAnnotation:validated_by
        # End of user code
        self._validated_by = set()
        # Start of user code attributeAnnotation:satisfied_by
        # End of user code
        self._satisfied_by = set()
        # Start of user code attributeAnnotation:satisfies
        # End of user code
        self._satisfies = set()
        # Start of user code attributeAnnotation:decomposed_by
        # End of user code
        self._decomposed_by = set()
        # Start of user code attributeAnnotation:decomposes
        # End of user code
        self._decomposes = set()
        # Start of user code attributeAnnotation:constrained_by
        # End of user code
        self._constrained_by = set()
        # Start of user code attributeAnnotation:constrains
        # End of user code
        self._constrains = set()
        
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:description
        # End of user code
        @oslc_name("description")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["description"])
        @oslc_description("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def description(self):
            # Start of user code getterInit:description
            # End of user code
            return self._description
    
        @description.setter
        def description(self, value: str):
            # Start of user code setterInit:description
            # End of user code
            self._description = value
            # Start of user code setterFinalize:description
            # End of user code
    
        @property
        # Start of user code getterAnnotation:identifier
        # End of user code
        @oslc_name("identifier")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["identifier"])
        @oslc_description("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def identifier(self):
            # Start of user code getterInit:identifier
            # End of user code
            return self._identifier
    
        @identifier.setter
        def identifier(self, value: str):
            # Start of user code setterInit:identifier
            # End of user code
            self._identifier = value
            # Start of user code setterFinalize:identifier
            # End of user code
    
        @property
        # Start of user code getterAnnotation:short_title
        # End of user code
        @oslc_name("shortTitle")
        @oslc_property_definition(oslc_constants.NS_OSLC["shortTitle"])
        @oslc_description("Shorter form of dcterms:title for the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def short_title(self):
            # Start of user code getterInit:short_title
            # End of user code
            return self._short_title
    
        @short_title.setter
        def short_title(self, value: str):
            # Start of user code setterInit:short_title
            # End of user code
            self._short_title = value
            # Start of user code setterFinalize:short_title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:subject
        # End of user code
        @oslc_name("subject")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["subject"])
        @oslc_description("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def subject(self):
            # Start of user code getterInit:subject
            # End of user code
            return self._subject
    
        @subject.setter
        def subject(self, value: Set[str]):
            # Start of user code setterInit:subject
            # End of user code
            self._subject = value
            # Start of user code setterFinalize:subject
            # End of user code
    
        @property
        # Start of user code getterAnnotation:creator
        # End of user code
        @oslc_name("creator")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["creator"])
        @oslc_description("Creator or creators of the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def creator(self):
            # Start of user code getterInit:creator
            # End of user code
            return self._creator
    
        @creator.setter
        def creator(self, value: Set[Link]):
            # Start of user code setterInit:creator
            # End of user code
            self._creator = value
            # Start of user code setterFinalize:creator
            # End of user code
    
        @property
        # Start of user code getterAnnotation:contributor
        # End of user code
        @oslc_name("contributor")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["contributor"])
        @oslc_description("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def contributor(self):
            # Start of user code getterInit:contributor
            # End of user code
            return self._contributor
    
        @contributor.setter
        def contributor(self, value: Set[Link]):
            # Start of user code setterInit:contributor
            # End of user code
            self._contributor = value
            # Start of user code setterFinalize:contributor
            # End of user code
    
        @property
        # Start of user code getterAnnotation:created
        # End of user code
        @oslc_name("created")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["created"])
        @oslc_description("Timestamp of resource creation")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def created(self):
            # Start of user code getterInit:created
            # End of user code
            return self._created
    
        @created.setter
        def created(self, value: datetime):
            # Start of user code setterInit:created
            # End of user code
            self._created = value
            # Start of user code setterFinalize:created
            # End of user code
    
        @property
        # Start of user code getterAnnotation:modified
        # End of user code
        @oslc_name("modified")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["modified"])
        @oslc_description("Timestamp of latest resource modification")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def modified(self):
            # Start of user code getterInit:modified
            # End of user code
            return self._modified
    
        @modified.setter
        def modified(self, value: datetime):
            # Start of user code setterInit:modified
            # End of user code
            self._modified = value
            # Start of user code setterFinalize:modified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:service_provider
        # End of user code
        @oslc_name("serviceProvider")
        @oslc_property_definition(oslc_constants.NS_OSLC["serviceProvider"])
        @oslc_description("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def service_provider(self):
            # Start of user code getterInit:service_provider
            # End of user code
            return self._service_provider
    
        @service_provider.setter
        def service_provider(self, value: Set[Link]):
            # Start of user code setterInit:service_provider
            # End of user code
            self._service_provider = value
            # Start of user code setterFinalize:service_provider
            # End of user code
    
        @property
        # Start of user code getterAnnotation:instance_shape
        # End of user code
        @oslc_name("instanceShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["instanceShape"])
        @oslc_description("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def instance_shape(self):
            # Start of user code getterInit:instance_shape
            # End of user code
            return self._instance_shape
    
        @instance_shape.setter
        def instance_shape(self, value: Set[Link]):
            # Start of user code setterInit:instance_shape
            # End of user code
            self._instance_shape = value
            # Start of user code setterFinalize:instance_shape
            # End of user code
    
        @property
        # Start of user code getterAnnotation:elaborated_by
        # End of user code
        @oslc_name("elaboratedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["elaboratedBy"])
        @oslc_description("The subject is elaborated by the object. For example, a user requirement is elaborated by use case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def elaborated_by(self):
            # Start of user code getterInit:elaborated_by
            # End of user code
            return self._elaborated_by
    
        @elaborated_by.setter
        def elaborated_by(self, value: Set[Link]):
            # Start of user code setterInit:elaborated_by
            # End of user code
            self._elaborated_by = value
            # Start of user code setterFinalize:elaborated_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:elaborates
        # End of user code
        @oslc_name("elaborates")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["elaborates"])
        @oslc_description("The object is elaborated by the subject.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def elaborates(self):
            # Start of user code getterInit:elaborates
            # End of user code
            return self._elaborates
    
        @elaborates.setter
        def elaborates(self, value: Set[Link]):
            # Start of user code setterInit:elaborates
            # End of user code
            self._elaborates = value
            # Start of user code setterFinalize:elaborates
            # End of user code
    
        @property
        # Start of user code getterAnnotation:specified_by
        # End of user code
        @oslc_name("specifiedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["specifiedBy"])
        @oslc_description("The subject is specified by the object. For example, a requirement is elaborated by a model element .")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def specified_by(self):
            # Start of user code getterInit:specified_by
            # End of user code
            return self._specified_by
    
        @specified_by.setter
        def specified_by(self, value: Set[Link]):
            # Start of user code setterInit:specified_by
            # End of user code
            self._specified_by = value
            # Start of user code setterFinalize:specified_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:specifies
        # End of user code
        @oslc_name("specifies")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["specifies"])
        @oslc_description("The object is specified by the subject.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def specifies(self):
            # Start of user code getterInit:specifies
            # End of user code
            return self._specifies
    
        @specifies.setter
        def specifies(self, value: Set[Link]):
            # Start of user code setterInit:specifies
            # End of user code
            self._specifies = value
            # Start of user code setterFinalize:specifies
            # End of user code
    
        @property
        # Start of user code getterAnnotation:affected_by
        # End of user code
        @oslc_name("affectedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["affectedBy"])
        @oslc_description("Requirement is affected by a resource, such as a defect or issue.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def affected_by(self):
            # Start of user code getterInit:affected_by
            # End of user code
            return self._affected_by
    
        @affected_by.setter
        def affected_by(self, value: Set[Link]):
            # Start of user code setterInit:affected_by
            # End of user code
            self._affected_by = value
            # Start of user code setterFinalize:affected_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:tracked_by
        # End of user code
        @oslc_name("trackedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["trackedBy"])
        @oslc_description("Resource, such as a change request, which tracks this requirement.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def tracked_by(self):
            # Start of user code getterInit:tracked_by
            # End of user code
            return self._tracked_by
    
        @tracked_by.setter
        def tracked_by(self, value: Set[Link]):
            # Start of user code setterInit:tracked_by
            # End of user code
            self._tracked_by = value
            # Start of user code setterFinalize:tracked_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:implemented_by
        # End of user code
        @oslc_name("implementedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["implementedBy"])
        @oslc_description("Resource, such as a change request, which implements this requirement.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def implemented_by(self):
            # Start of user code getterInit:implemented_by
            # End of user code
            return self._implemented_by
    
        @implemented_by.setter
        def implemented_by(self, value: Set[Link]):
            # Start of user code setterInit:implemented_by
            # End of user code
            self._implemented_by = value
            # Start of user code setterFinalize:implemented_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:validated_by
        # End of user code
        @oslc_name("validatedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["validatedBy"])
        @oslc_description("Resource, such as a test case, which validates this requirement.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def validated_by(self):
            # Start of user code getterInit:validated_by
            # End of user code
            return self._validated_by
    
        @validated_by.setter
        def validated_by(self, value: Set[Link]):
            # Start of user code setterInit:validated_by
            # End of user code
            self._validated_by = value
            # Start of user code setterFinalize:validated_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:satisfied_by
        # End of user code
        @oslc_name("satisfiedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["satisfiedBy"])
        @oslc_description("The subject is satisfied by the object. For example, a user requirement is satisfied by a system requirement.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def satisfied_by(self):
            # Start of user code getterInit:satisfied_by
            # End of user code
            return self._satisfied_by
    
        @satisfied_by.setter
        def satisfied_by(self, value: Set[Link]):
            # Start of user code setterInit:satisfied_by
            # End of user code
            self._satisfied_by = value
            # Start of user code setterFinalize:satisfied_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:satisfies
        # End of user code
        @oslc_name("satisfies")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["satisfies"])
        @oslc_description("The object is satisfied by the subject.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def satisfies(self):
            # Start of user code getterInit:satisfies
            # End of user code
            return self._satisfies
    
        @satisfies.setter
        def satisfies(self, value: Set[Link]):
            # Start of user code setterInit:satisfies
            # End of user code
            self._satisfies = value
            # Start of user code setterFinalize:satisfies
            # End of user code
    
        @property
        # Start of user code getterAnnotation:decomposed_by
        # End of user code
        @oslc_name("decomposedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["decomposedBy"])
        @oslc_description("The subject is decomposed by the object. For example, a system requirement is decomposed into a collection of system requirements.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def decomposed_by(self):
            # Start of user code getterInit:decomposed_by
            # End of user code
            return self._decomposed_by
    
        @decomposed_by.setter
        def decomposed_by(self, value: Set[Link]):
            # Start of user code setterInit:decomposed_by
            # End of user code
            self._decomposed_by = value
            # Start of user code setterFinalize:decomposed_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:decomposes
        # End of user code
        @oslc_name("decomposes")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["decomposes"])
        @oslc_description("The object is decomposed by the subject.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def decomposes(self):
            # Start of user code getterInit:decomposes
            # End of user code
            return self._decomposes
    
        @decomposes.setter
        def decomposes(self, value: Set[Link]):
            # Start of user code setterInit:decomposes
            # End of user code
            self._decomposes = value
            # Start of user code setterFinalize:decomposes
            # End of user code
    
        @property
        # Start of user code getterAnnotation:constrained_by
        # End of user code
        @oslc_name("constrainedBy")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["constrainedBy"])
        @oslc_description("The subject is constrained by the object. For example, a functional requirement is constrained by a safety requirement.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def constrained_by(self):
            # Start of user code getterInit:constrained_by
            # End of user code
            return self._constrained_by
    
        @constrained_by.setter
        def constrained_by(self, value: Set[Link]):
            # Start of user code setterInit:constrained_by
            # End of user code
            self._constrained_by = value
            # Start of user code setterFinalize:constrained_by
            # End of user code
    
        @property
        # Start of user code getterAnnotation:constrains
        # End of user code
        @oslc_name("constrains")
        @oslc_property_definition(oslc_rm_vocabulary_constants.NS_OSLC_RM["constrains"])
        @oslc_description("The object is constrained by the subject.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def constrains(self):
            # Start of user code getterInit:constrains
            # End of user code
            return self._constrains
    
        @constrains.setter
        def constrains(self, value: Set[Link]):
            # Start of user code setterInit:constrains
            # End of user code
            self._constrains = value
            # Start of user code setterFinalize:constrains
            # End of user code
    
    
