/**
 *
 * $Id$
 */
package vocabulary.validation;

import org.eclipse.emf.common.util.EList;

import vocabulary.Property;

/**
 * A sample validator interface for {@link vocabulary.Property}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PropertyValidator {
	boolean validate();

	boolean validateSubPropertyOf(EList<Property> value);
	boolean validateDomain(EList<vocabulary.Class> value);
	boolean validateRange(EList<vocabulary.Class> value);
}
