/**
 *
 * $Id$
 */
package vocabulary.validation;

import org.eclipse.emf.common.util.EList;

import vocabulary.Property;

/**
 * A sample validator interface for {@link vocabulary.Vocabulary}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface VocabularyValidator {
    boolean validate();

    boolean validateNamespaceURI(String value);
    boolean validateLabel(String value);
    boolean validateDescription(String value);
    boolean validateSource(String value);
    boolean validatePreferredNamespacePrefix(String value);
    boolean validateClasses(EList<vocabulary.Class> value);
    boolean validateProperties(EList<Property> value);
}
