/**
 *
 * $Id$
 */
package adaptorinterface.validation;

import adaptorinterface.Resource;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link adaptorinterface.CreationFactory}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface CreationFactoryValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateLabel(String value);
	boolean validateCreationURI(String value);
	boolean validateResourceTypes(EList<Resource> value);
	boolean validateUsages(EList<String> value);
}
