/**
 *
 * $Id$
 */
package adaptorinterface.validation;

import adaptorinterface.GenerationSetting;
import adaptorinterface.NamespacePrefix;
import adaptorinterface.Resource;
import adaptorinterface.ResourceProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link adaptorinterface.DomainSpecification}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DomainSpecificationValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateNamespaceURI(String value);
	boolean validateNamespacePrefix(NamespacePrefix value);
	boolean validateResources(EList<Resource> value);
	boolean validateResourceProperties(EList<ResourceProperty> value);
	boolean validateGenerationSetting(GenerationSetting value);
}
