/**
 *
 * $Id$
 */
package adaptorinterface.validation;


/**
 * A sample validator interface for {@link adaptorinterface.Publisher}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface PublisherValidator {
	boolean validate();

	boolean validateTitle(String value);
	boolean validateLabel(String value);
	boolean validateIdentifier(String value);
	boolean validateIcon(String value);
}
