/**
 *
 * $Id$
 */
package adaptorinterface.validation;

import adaptorinterface.Resource;
import adaptorinterface.ResourceProperty;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link adaptorinterface.Resource}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ResourceValidator {
	boolean validate();

	boolean validateName(String value);
	boolean validateExtends(EList<Resource> value);
	boolean validateResourceProperties(EList<ResourceProperty> value);
	boolean validateDescribes(vocabulary.Class value);
}
