# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.dcterms_vocabulary_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.rdf_vocabulary_constants import NS_RDF
from org.eclipse.lyo.oslc.domains.auto.AutomationPlan import AutomationPlan
from org.eclipse.lyo.oslc.domains.auto.AutomationRequest import AutomationRequest
from org.eclipse.lyo.oslc.domains.auto.Contribution import Contribution
from org.eclipse.lyo.oslc.domains.auto.ParameterInstance import ParameterInstance
from org.eclipse.lyo.oslc.domains.Person import Person
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_AUTO)
@oslc_name("AutomationResult")
@oslc_resource_shape(describes=NS_OSLC_AUTO["AutomationResult"], title="AutomationResult Shape")
class AutomationResult(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:contributor
        # End of user code
        self._contributor = set()
        # Start of user code attributeAnnotation:created
        # End of user code
        self._created = None
        # Start of user code attributeAnnotation:creator
        # End of user code
        self._creator = set()
        # Start of user code attributeAnnotation:identifier
        # End of user code
        self._identifier = None
        # Start of user code attributeAnnotation:modified
        # End of user code
        self._modified = None
        # Start of user code attributeAnnotation:type
        # End of user code
        self._type = set()
        # Start of user code attributeAnnotation:subject
        # End of user code
        self._subject = set()
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:instance_shape
        # End of user code
        self._instance_shape = set()
        # Start of user code attributeAnnotation:service_provider
        # End of user code
        self._service_provider = set()
        # Start of user code attributeAnnotation:state
        # End of user code
        self._state = set()
        # Start of user code attributeAnnotation:desired_state
        # End of user code
        self._desired_state = None
        # Start of user code attributeAnnotation:verdict
        # End of user code
        self._verdict = set()
        # Start of user code attributeAnnotation:contribution
        # End of user code
        self._contribution = set()
        # Start of user code attributeAnnotation:input_parameter
        # End of user code
        self._input_parameter = set()
        # Start of user code attributeAnnotation:output_parameter
        # End of user code
        self._output_parameter = set()
        # Start of user code attributeAnnotation:produced_by_automation_request
        # End of user code
        self._produced_by_automation_request = None
        # Start of user code attributeAnnotation:reports_on_automation_plan
        # End of user code
        self._reports_on_automation_plan = None
        # 
        self._ = None
        
        @property
        # Start of user code getterAnnotation:contributor
        # End of user code
        @oslc_name("contributor")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["contributor"])
        @oslc_description("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def contributor(self):
            # Start of user code getterInit:contributor
            # End of user code
            return self._contributor
    
        @contributor.setter
        def contributor(self, value: Set[Link]):
            # Start of user code setterInit:contributor
            # End of user code
            self._contributor = value
            # Start of user code setterFinalize:contributor
            # End of user code
    
        @property
        # Start of user code getterAnnotation:created
        # End of user code
        @oslc_name("created")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["created"])
        @oslc_description("Timestamp of resource creation")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def created(self):
            # Start of user code getterInit:created
            # End of user code
            return self._created
    
        @created.setter
        def created(self, value: datetime):
            # Start of user code setterInit:created
            # End of user code
            self._created = value
            # Start of user code setterFinalize:created
            # End of user code
    
        @property
        # Start of user code getterAnnotation:creator
        # End of user code
        @oslc_name("creator")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["creator"])
        @oslc_description("Creator or creators of the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def creator(self):
            # Start of user code getterInit:creator
            # End of user code
            return self._creator
    
        @creator.setter
        def creator(self, value: Set[Link]):
            # Start of user code setterInit:creator
            # End of user code
            self._creator = value
            # Start of user code setterFinalize:creator
            # End of user code
    
        @property
        # Start of user code getterAnnotation:identifier
        # End of user code
        @oslc_name("identifier")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["identifier"])
        @oslc_description("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def identifier(self):
            # Start of user code getterInit:identifier
            # End of user code
            return self._identifier
    
        @identifier.setter
        def identifier(self, value: str):
            # Start of user code setterInit:identifier
            # End of user code
            self._identifier = value
            # Start of user code setterFinalize:identifier
            # End of user code
    
        @property
        # Start of user code getterAnnotation:modified
        # End of user code
        @oslc_name("modified")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["modified"])
        @oslc_description("Timestamp of latest resource modification")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def modified(self):
            # Start of user code getterInit:modified
            # End of user code
            return self._modified
    
        @modified.setter
        def modified(self, value: datetime):
            # Start of user code setterInit:modified
            # End of user code
            self._modified = value
            # Start of user code setterFinalize:modified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:type
        # End of user code
        @oslc_name("type")
        @oslc_property_definition(rdf_vocabulary_constants.NS_RDF["type"])
        @oslc_description("The resource type URIs")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def type(self):
            # Start of user code getterInit:type
            # End of user code
            return self._type
    
        @type.setter
        def type(self, value: Set[Link]):
            # Start of user code setterInit:type
            # End of user code
            self._type = value
            # Start of user code setterFinalize:type
            # End of user code
    
        @property
        # Start of user code getterAnnotation:subject
        # End of user code
        @oslc_name("subject")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["subject"])
        @oslc_description("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def subject(self):
            # Start of user code getterInit:subject
            # End of user code
            return self._subject
    
        @subject.setter
        def subject(self, value: Set[str]):
            # Start of user code setterInit:subject
            # End of user code
            self._subject = value
            # Start of user code setterFinalize:subject
            # End of user code
    
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:instance_shape
        # End of user code
        @oslc_name("instanceShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["instanceShape"])
        @oslc_description("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def instance_shape(self):
            # Start of user code getterInit:instance_shape
            # End of user code
            return self._instance_shape
    
        @instance_shape.setter
        def instance_shape(self, value: Set[Link]):
            # Start of user code setterInit:instance_shape
            # End of user code
            self._instance_shape = value
            # Start of user code setterFinalize:instance_shape
            # End of user code
    
        @property
        # Start of user code getterAnnotation:service_provider
        # End of user code
        @oslc_name("serviceProvider")
        @oslc_property_definition(oslc_constants.NS_OSLC["serviceProvider"])
        @oslc_description("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def service_provider(self):
            # Start of user code getterInit:service_provider
            # End of user code
            return self._service_provider
    
        @service_provider.setter
        def service_provider(self, value: Set[Link]):
            # Start of user code setterInit:service_provider
            # End of user code
            self._service_provider = value
            # Start of user code setterFinalize:service_provider
            # End of user code
    
        @property
        # Start of user code getterAnnotation:state
        # End of user code
        @oslc_name("state")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["state"])
        @oslc_description("Used to indicate the state of the automation request based on values defined by the service provider. Most often a read-only property. It is expected that this will be a resource reference to a definition of a valid automation request state on the service provider.")
        @oslc_occurs(Occurs.ONE_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(True)
        def state(self):
            # Start of user code getterInit:state
            # End of user code
            return self._state
    
        @state.setter
        def state(self, value: Set[Link]):
            # Start of user code setterInit:state
            # End of user code
            self._state = value
            # Start of user code setterFinalize:state
            # End of user code
    
        @property
        # Start of user code getterAnnotation:desired_state
        # End of user code
        @oslc_name("desiredState")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["desiredState"])
        @oslc_description("Used to indicate the desired state of the Automation Request based on values defined by the service provider. It is expected that this will be a resource reference to a definition of a valid automation request state on the service provider.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def desired_state(self):
            # Start of user code getterInit:desired_state
            # End of user code
            return self._desired_state
    
        @desired_state.setter
        def desired_state(self, value: Link):
            # Start of user code setterInit:desired_state
            # End of user code
            self._desired_state = value
            # Start of user code setterFinalize:desired_state
            # End of user code
    
        @property
        # Start of user code getterAnnotation:verdict
        # End of user code
        @oslc_name("verdict")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["verdict"])
        @oslc_description("Used to indicate the verdict of the automation result based on values defined by the service provider. Most often a read-only property. It is expected that this will be a resource reference to a definition of a valid automation result verdict on the service provider.")
        @oslc_occurs(Occurs.ONE_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def verdict(self):
            # Start of user code getterInit:verdict
            # End of user code
            return self._verdict
    
        @verdict.setter
        def verdict(self, value: Set[Link]):
            # Start of user code setterInit:verdict
            # End of user code
            self._verdict = value
            # Start of user code setterFinalize:verdict
            # End of user code
    
        @property
        # Start of user code getterAnnotation:contribution
        # End of user code
        @oslc_name("contribution")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["contribution"])
        @oslc_description("A result contribution associated with this automation result. It is recommended that the contribution be an inline resource which can be retrieved with the automation result. The recommended attributes beyond the contribution itself are dcterms:title, dcterms:description and dcterms:type to provide a description of the contribution which would be appropriate for display in a simple UI for an automation result.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.LocalResource)
        @oslc_range(oslc_auto_constants[CONTRIBUTION_TYPE])
        @oslc_read_only(False)
        def contribution(self):
            # Start of user code getterInit:contribution
            # End of user code
            return self._contribution
    
        @contribution.setter
        def contribution(self, value: Set[Contribution]):
            # Start of user code setterInit:contribution
            # End of user code
            self._contribution = value
            # Start of user code setterFinalize:contribution
            # End of user code
    
        @property
        # Start of user code getterAnnotation:input_parameter
        # End of user code
        @oslc_name("inputParameter")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["inputParameter"])
        @oslc_description("Parameters provided when Automation Requests are created. These include parameters provided by the creator of the Automation Request (whether by delegated UI or HTTP POST) and MAY include additional parameters added by the service provider during Automation Request creation. See the definition of the oslc_auto:parameterDefinition attribute of the Automation Plan for additional guidance on determining which parameters are required. Creators of Automation Requests MAY provide parameters beyond those defined in the Automation Plan without guarantee the service provider will recognize or honor them. It is expected that this attribute is write-able on Automation Request creation and read-only thereafter.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.LocalResource)
        @oslc_range(oslc_auto_constants[PARAMETERINSTANCE_TYPE])
        @oslc_read_only(False)
        def input_parameter(self):
            # Start of user code getterInit:input_parameter
            # End of user code
            return self._input_parameter
    
        @input_parameter.setter
        def input_parameter(self, value: Set[ParameterInstance]):
            # Start of user code setterInit:input_parameter
            # End of user code
            self._input_parameter = value
            # Start of user code setterFinalize:input_parameter
            # End of user code
    
        @property
        # Start of user code getterAnnotation:output_parameter
        # End of user code
        @oslc_name("outputParameter")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["outputParameter"])
        @oslc_description("Automation Result output parameters are parameters associated with the automation execution which produced this Result. This includes the final value of all parameters used to initiate the execution and any additional parameters which may have been created during automation execution by the service provider or external agents. The value of a given oslc_auto:outputParameter MAY change as the execution proceeds. Point-in-time accuracy of the values of output parameters is not covered by this specification. Once the Automation Result is in a final state ( oslc_auto:complete or oslc_auto:canceled), the oslc_auto:outputParameter values MUST NOT change.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.LocalResource)
        @oslc_range(oslc_auto_constants[PARAMETERINSTANCE_TYPE])
        @oslc_read_only(False)
        def output_parameter(self):
            # Start of user code getterInit:output_parameter
            # End of user code
            return self._output_parameter
    
        @output_parameter.setter
        def output_parameter(self, value: Set[ParameterInstance]):
            # Start of user code setterInit:output_parameter
            # End of user code
            self._output_parameter = value
            # Start of user code setterFinalize:output_parameter
            # End of user code
    
        @property
        # Start of user code getterAnnotation:produced_by_automation_request
        # End of user code
        @oslc_name("producedByAutomationRequest")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["producedByAutomationRequest"])
        @oslc_description("Automation Request which produced the Automation Result. It is likely that the target resource will be an oslc_auto:AutomationRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_auto_constants[AUTOMATIONREQUEST_TYPE])
        @oslc_read_only(False)
        def produced_by_automation_request(self):
            # Start of user code getterInit:produced_by_automation_request
            # End of user code
            return self._produced_by_automation_request
    
        @produced_by_automation_request.setter
        def produced_by_automation_request(self, value: Link):
            # Start of user code setterInit:produced_by_automation_request
            # End of user code
            self._produced_by_automation_request = value
            # Start of user code setterFinalize:produced_by_automation_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:reports_on_automation_plan
        # End of user code
        @oslc_name("reportsOnAutomationPlan")
        @oslc_property_definition(oslc_auto_constants.NS_OSLC_AUTO["reportsOnAutomationPlan"])
        @oslc_description("Automation Plan which the Automation Result reports on. It is likely that the target resource will be an oslc_auto:AutomationPlan but that is not necessarily the case.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_auto_constants[AUTOMATIONPLAN_TYPE])
        @oslc_read_only(False)
        def reports_on_automation_plan(self):
            # Start of user code getterInit:reports_on_automation_plan
            # End of user code
            return self._reports_on_automation_plan
    
        @reports_on_automation_plan.setter
        def reports_on_automation_plan(self, value: Link):
            # Start of user code setterInit:reports_on_automation_plan
            # End of user code
            self._reports_on_automation_plan = value
            # Start of user code setterFinalize:reports_on_automation_plan
            # End of user code
    
        @property
        # 
        
        
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def (self):
            # 
            return self._
    
        @.setter
        def (self, value: bool):
            # 
            self._ = value
            # 
    
    
