# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.dcterms_vocabulary_constants import NS_DCTERMS
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_AUTO)
@oslc_name("ParameterDefinition")
@oslc_resource_shape(describes=NS_OSLC_AUTO["ParameterDefinition"], title="ParameterDefinition Shape")
class ParameterDefinition(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:description
        # End of user code
        self._description = None
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:allowed_value
        # End of user code
        self._allowed_value = set()
        # Start of user code attributeAnnotation:default_value
        # End of user code
        self._default_value = None
        # Start of user code attributeAnnotation:allowed_values
        # End of user code
        self._allowed_values = None
        # Start of user code attributeAnnotation:hidden
        # End of user code
        self._hidden = None
        # Start of user code attributeAnnotation:is_member_property
        # End of user code
        self._is_member_property = None
        # Start of user code attributeAnnotation:name
        # End of user code
        self._name = None
        # Start of user code attributeAnnotation:max_size
        # End of user code
        self._max_size = None
        # Start of user code attributeAnnotation:occurs
        # End of user code
        self._occurs = None
        # Start of user code attributeAnnotation:range
        # End of user code
        self._range = set()
        # Start of user code attributeAnnotation:read_only
        # End of user code
        self._read_only = None
        # Start of user code attributeAnnotation:representation
        # End of user code
        self._representation = None
        # Start of user code attributeAnnotation:value_type
        # End of user code
        self._value_type = set()
        # Start of user code attributeAnnotation:value_shape
        # End of user code
        self._value_shape = None
        # 
        self._ = None
        # Start of user code attributeAnnotation:property_definition
        # End of user code
        self._property_definition = None
        # 
        self._ = None
        
        @property
        # Start of user code getterAnnotation:description
        # End of user code
        @oslc_name("description")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["description"])
        @oslc_description("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def description(self):
            # Start of user code getterInit:description
            # End of user code
            return self._description
    
        @description.setter
        def description(self, value: str):
            # Start of user code setterInit:description
            # End of user code
            self._description = value
            # Start of user code setterFinalize:description
            # End of user code
    
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:allowed_value
        # End of user code
        @oslc_name("allowedValue")
        @oslc_property_definition(oslc_constants.NS_OSLC["allowedValue"])
        @oslc_description("value allowed for a property")
        @oslc_occurs(Occurs.ONE_OR_MANY)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def allowed_value(self):
            # Start of user code getterInit:allowed_value
            # End of user code
            return self._allowed_value
    
        @allowed_value.setter
        def allowed_value(self, value: Set[str]):
            # Start of user code setterInit:allowed_value
            # End of user code
            self._allowed_value = value
            # Start of user code setterFinalize:allowed_value
            # End of user code
    
        @property
        # Start of user code getterAnnotation:default_value
        # End of user code
        @oslc_name("defaultValue")
        @oslc_property_definition(oslc_constants.NS_OSLC["defaultValue"])
        @oslc_description("A default value for property, inlined into property definition. ")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def default_value(self):
            # Start of user code getterInit:default_value
            # End of user code
            return self._default_value
    
        @default_value.setter
        def default_value(self, value: str):
            # Start of user code setterInit:default_value
            # End of user code
            self._default_value = value
            # Start of user code setterFinalize:default_value
            # End of user code
    
        @property
        # Start of user code getterAnnotation:allowed_values
        # End of user code
        @oslc_name("allowedValues")
        @oslc_property_definition(oslc_constants.NS_OSLC["allowedValues"])
        @oslc_description("Resource with allowed values for the property being defined. ")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def allowed_values(self):
            # Start of user code getterInit:allowed_values
            # End of user code
            return self._allowed_values
    
        @allowed_values.setter
        def allowed_values(self, value: Link):
            # Start of user code setterInit:allowed_values
            # End of user code
            self._allowed_values = value
            # Start of user code setterFinalize:allowed_values
            # End of user code
    
        @property
        # Start of user code getterAnnotation:hidden
        # End of user code
        @oslc_name("hidden")
        @oslc_property_definition(oslc_constants.NS_OSLC["hidden"])
        @oslc_description("A hint that indicates that property MAY be hidden when presented in a user interface ")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def hidden(self):
            # Start of user code getterInit:hidden
            # End of user code
            return self._hidden
    
        @hidden.setter
        def hidden(self, value: bool):
            # Start of user code setterInit:hidden
            # End of user code
            self._hidden = value
            # Start of user code setterFinalize:hidden
            # End of user code
    
        @property
        # Start of user code getterAnnotation:is_member_property
        # End of user code
        @oslc_name("isMemberProperty")
        @oslc_property_definition(oslc_constants.NS_OSLC["isMemberProperty"])
        @oslc_description("If set to true, this indicates that the property is a membership property, as described in the Query Syntax Specification: Member List Patterns. This is useful when the resource whose shape is being defined is viewed as a container of other resources. For example, look at the last example in Appendix B's RDF/XML Representation Examples: Specifying the shape of a query result, where blog:comment is defined as a membership property and comment that matches the query is returned as value of that property.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def is_member_property(self):
            # Start of user code getterInit:is_member_property
            # End of user code
            return self._is_member_property
    
        @is_member_property.setter
        def is_member_property(self, value: bool):
            # Start of user code setterInit:is_member_property
            # End of user code
            self._is_member_property = value
            # Start of user code setterFinalize:is_member_property
            # End of user code
    
        @property
        # Start of user code getterAnnotation:name
        # End of user code
        @oslc_name("name")
        @oslc_property_definition(oslc_constants.NS_OSLC["name"])
        @oslc_description("Name of property being defined, i.e. second part of property's Prefixed Name")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def name(self):
            # Start of user code getterInit:name
            # End of user code
            return self._name
    
        @name.setter
        def name(self, value: str):
            # Start of user code setterInit:name
            # End of user code
            self._name = value
            # Start of user code setterFinalize:name
            # End of user code
    
        @property
        # Start of user code getterAnnotation:max_size
        # End of user code
        @oslc_name("maxSize")
        @oslc_property_definition(oslc_constants.NS_OSLC["maxSize"])
        @oslc_description("For String properties only, specifies maximum characters allowed. If not set, then there is no maximum or maximum is specified elsewhere.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Integer)
        @oslc_read_only(False)
        def max_size(self):
            # Start of user code getterInit:max_size
            # End of user code
            return self._max_size
    
        @max_size.setter
        def max_size(self, value: int):
            # Start of user code setterInit:max_size
            # End of user code
            self._max_size = value
            # Start of user code setterFinalize:max_size
            # End of user code
    
        @property
        # Start of user code getterAnnotation:occurs
        # End of user code
        @oslc_name("occurs")
        @oslc_property_definition(oslc_constants.NS_OSLC["occurs"])
        @oslc_description("MUST be either http://open-services.net/ns/core#Exactly-one (property is required), http://open-services.net/ns/core#Zero-or-one (property is optional), http://open-services.net/ns/core#zeroOrMany (property is optional), or http://open-services.net/ns/core#One-or-many (property is required)")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def occurs(self):
            # Start of user code getterInit:occurs
            # End of user code
            return self._occurs
    
        @occurs.setter
        def occurs(self, value: Link):
            # Start of user code setterInit:occurs
            # End of user code
            self._occurs = value
            # Start of user code setterFinalize:occurs
            # End of user code
    
        @property
        # Start of user code getterAnnotation:range
        # End of user code
        @oslc_name("range")
        @oslc_property_definition(oslc_constants.NS_OSLC["range"])
        @oslc_description("For properties with a resource value-type, Providers MAY also specify the range of possible resource types allowed, each specified by URI. The default range is http://open-services.net/ns/core#Any.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def range(self):
            # Start of user code getterInit:range
            # End of user code
            return self._range
    
        @range.setter
        def range(self, value: Set[Link]):
            # Start of user code setterInit:range
            # End of user code
            self._range = value
            # Start of user code setterFinalize:range
            # End of user code
    
        @property
        # Start of user code getterAnnotation:read_only
        # End of user code
        @oslc_name("readOnly")
        @oslc_property_definition(oslc_constants.NS_OSLC["readOnly"])
        @oslc_description("true if the property is read-only. If omitted, or set to false, then the property is writable. Providers SHOULD declare a property read-only when changes to the value of that property will not be accepted after the resource has been created, e.g. on PUT/PATCH requests. Consumers should note that the converse does not apply: Providers MAY reject a change to the value of a writable property.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def read_only(self):
            # Start of user code getterInit:read_only
            # End of user code
            return self._read_only
    
        @read_only.setter
        def read_only(self, value: bool):
            # Start of user code setterInit:read_only
            # End of user code
            self._read_only = value
            # Start of user code setterFinalize:read_only
            # End of user code
    
        @property
        # Start of user code getterAnnotation:representation
        # End of user code
        @oslc_name("representation")
        @oslc_property_definition(oslc_constants.NS_OSLC["representation"])
        @oslc_description("Should be http://open-services.net/ns/core#Reference, http://open-services.net/ns/core#Inline or http://open-services.net/ns/core#Either")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def representation(self):
            # Start of user code getterInit:representation
            # End of user code
            return self._representation
    
        @representation.setter
        def representation(self, value: Link):
            # Start of user code setterInit:representation
            # End of user code
            self._representation = value
            # Start of user code setterFinalize:representation
            # End of user code
    
        @property
        # Start of user code getterAnnotation:value_type
        # End of user code
        @oslc_name("valueType")
        @oslc_property_definition(oslc_constants.NS_OSLC["valueType"])
        @oslc_description("See below for list of allowed values for oslc:valueType. If this property is omitted, then the value type is unconstrained.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def value_type(self):
            # Start of user code getterInit:value_type
            # End of user code
            return self._value_type
    
        @value_type.setter
        def value_type(self, value: Set[Link]):
            # Start of user code setterInit:value_type
            # End of user code
            self._value_type = value
            # Start of user code setterFinalize:value_type
            # End of user code
    
        @property
        # Start of user code getterAnnotation:value_shape
        # End of user code
        @oslc_name("valueShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["valueShape"])
        @oslc_description("if the value-type is a resource type, then Property MAY provide a shape value to indicate the Resource Shape that applies to the resource.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def value_shape(self):
            # Start of user code getterInit:value_shape
            # End of user code
            return self._value_shape
    
        @value_shape.setter
        def value_shape(self, value: Link):
            # Start of user code setterInit:value_shape
            # End of user code
            self._value_shape = value
            # Start of user code setterFinalize:value_shape
            # End of user code
    
        @property
        # 
        
        
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def (self):
            # 
            return self._
    
        @.setter
        def (self, value: bool):
            # 
            self._ = value
            # 
    
        @property
        # Start of user code getterAnnotation:property_definition
        # End of user code
        @oslc_name("propertyDefinition")
        @oslc_property_definition(oslc_constants.NS_OSLC["propertyDefinition"])
        @oslc_description("URI of the property whose usage is being described.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def property_definition(self):
            # Start of user code getterInit:property_definition
            # End of user code
            return self._property_definition
    
        @property_definition.setter
        def property_definition(self, value: Link):
            # Start of user code setterInit:property_definition
            # End of user code
            self._property_definition = value
            # Start of user code setterFinalize:property_definition
            # End of user code
    
        @property
        # 
        
        
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Boolean)
        @oslc_read_only(False)
        def (self):
            # 
            return self._
    
        @.setter
        def (self, value: bool):
            # 
            self._ = value
            # 
    
    
