// Start of user code Copyright
/*******************************************************************************
 * Copyright (c) 2012 IBM Corporation and others.
 *
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * and Eclipse Distribution License v. 1.0 which accompanies this distribution.
 *  
 * The Eclipse Public License is available at http://www.eclipse.org/legal/epl-v10.html
 * and the Eclipse Distribution License is available at
 * http://www.eclipse.org/org/documents/edl-v10.php.
 *
 * Contributors:
 *
 *     Russell Boykin       - initial API and implementation
 *     Alberto Giammaria    - initial API and implementation
 *     Chris Peters         - initial API and implementation
 *     Gianluca Bernardini  - initial API and implementation
 *     Michael Fiedler      - Bugzilla adpater implementations
 *     Jad El-khoury        - initial implementation of code generator (https://bugs.eclipse.org/bugs/show_bug.cgi?id=422448)
 * 
 * This file is generated by org.eclipse.lyo.oslc4j.codegenerator
 *******************************************************************************/
// End of user code

package org.eclipse.lyo.tools.emf2rdf.resources;

import org.eclipse.lyo.oslc4j.core.model.OslcConstants;


// Start of user code imports
// End of user code

public interface OwlDomainConstants
{
    // Start of user code user constants
    // End of user code

    public static String OWL_DOMAIN = "http://www.w3.org/2002/07/owl#";
    public static String OWL_NAMSPACE = "http://www.w3.org/2002/07/owl#";
    public static String OWL_NAMSPACE_PREFIX = "owl";

    public static String ONTOLOGY_PATH = "ontology";
    public static String ONTOLOGY_NAMESPACE = OWL_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String ONTOLOGY_LOCALNAME = "Ontology"; //localName of the rdfs:class the resource describes
    public static String ONTOLOGY_TYPE = ONTOLOGY_NAMESPACE + ONTOLOGY_LOCALNAME; //fullname of the rdfs:class the resource describes
    public static String VOCABULARIES_PATH = "vocabularies";
    public static String VOCABULARIES_NAMESPACE = OWL_NAMSPACE; //namespace of the rdfs:class the resource describes
    public static String VOCABULARIES_LOCALNAME = "Vocabularies"; //localName of the rdfs:class the resource describes
    public static String VOCABULARIES_TYPE = VOCABULARIES_NAMESPACE + VOCABULARIES_LOCALNAME; //fullname of the rdfs:class the resource describes
}
