# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.foaf_constants import NS_FOAF
from org.eclipse.lyo.oslc.domains.foaf_vocabulary_constants import NS_FOAF
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_FOAF)
@oslc_name("Agent")
@oslc_resource_shape(describes=NS_FOAF["Agent"], title="Agent Shape")
class Agent(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:name
        # End of user code
        self._name = None
        
        @property
        # Start of user code getterAnnotation:name
        # End of user code
        @oslc_name("name")
        @oslc_property_definition(foaf_vocabulary_constants.NS_FOAF["name"])
        @oslc_description("The full name of a person expressed as simple text string.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def name(self):
            # Start of user code getterInit:name
            # End of user code
            return self._name
    
        @name.setter
        def name(self, value: str):
            # Start of user code setterInit:name
            # End of user code
            self._name = value
            # Start of user code setterFinalize:name
            # End of user code
    
    
