# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.rdfs_constants import NS_RDFS
from org.eclipse.lyo.oslc.domains.rdfs_vocabulary_constants import NS_RDFS
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_RDFS)
@oslc_name("Class")
@oslc_resource_shape(describes=NS_RDFS["Class"], title="Class Shape")
class Class(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:sub_class_of
        # End of user code
        self._sub_class_of = None
        
        @property
        # Start of user code getterAnnotation:sub_class_of
        # End of user code
        @oslc_name("subClassOf")
        @oslc_property_definition(rdfs_vocabulary_constants.NS_RDFS["subClassOf"])
        @oslc_description("used to state that all the instances of one class are instances of another")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(rdfs_constants[CLASS_TYPE])
        @oslc_read_only(False)
        def sub_class_of(self):
            # Start of user code getterInit:sub_class_of
            # End of user code
            return self._sub_class_of
    
        @sub_class_of.setter
        def sub_class_of(self, value: Link):
            # Start of user code setterInit:sub_class_of
            # End of user code
            self._sub_class_of = value
            # Start of user code setterFinalize:sub_class_of
            # End of user code
    
    
