# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.cm.oslc_cm_constants import NS_OSLC_CM
from org.eclipse.lyo.oslc.domains.dcterms_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.foaf_constants import NS_FOAF
from org.eclipse.lyo.oslc4j.core.model.oslc_constants import NS_OSLC
from org.eclipse.lyo.oslc.domains.qm.oslc_qm_constants import NS_OSLC_QM
from org.eclipse.lyo.oslc.domains.rdf_constants import NS_RDF
from org.eclipse.lyo.oslc.domains.dcterms_vocabulary_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.oslc_qm_vocabulary_constants import NS_OSLC_QM
from org.eclipse.lyo.oslc.domains.rdf_vocabulary_constants import NS_RDF
from org.eclipse.lyo.oslc.domains.cm.ChangeRequest import ChangeRequest
from org.eclipse.lyo.oslc.domains.Person import Person
from org.eclipse.lyo.oslc.domains.qm.TestCase import TestCase
from org.eclipse.lyo.oslc.domains.qm.TestPlan import TestPlan
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_QM)
@oslc_name("TestExecutionRecord")
@oslc_resource_shape(describes=NS_OSLC_QM["TestExecutionRecord"], title="TestExecutionRecord Shape")
class TestExecutionRecord(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:contributor
        # End of user code
        self._contributor = set()
        # Start of user code attributeAnnotation:created
        # End of user code
        self._created = None
        # Start of user code attributeAnnotation:creator
        # End of user code
        self._creator = set()
        # Start of user code attributeAnnotation:identifier
        # End of user code
        self._identifier = None
        # Start of user code attributeAnnotation:modified
        # End of user code
        self._modified = None
        # Start of user code attributeAnnotation:type
        # End of user code
        self._type = set()
        # Start of user code attributeAnnotation:instance_shape
        # End of user code
        self._instance_shape = set()
        # Start of user code attributeAnnotation:service_provider
        # End of user code
        self._service_provider = set()
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:blocked_by_change_request
        # End of user code
        self._blocked_by_change_request = set()
        # Start of user code attributeAnnotation:related_change_request
        # End of user code
        self._related_change_request = set()
        # Start of user code attributeAnnotation:reports_on_test_plan
        # End of user code
        self._reports_on_test_plan = None
        # Start of user code attributeAnnotation:runs_on_test_environment
        # End of user code
        self._runs_on_test_environment = None
        # Start of user code attributeAnnotation:runs_test_case
        # End of user code
        self._runs_test_case = None
        
        @property
        # Start of user code getterAnnotation:contributor
        # End of user code
        @oslc_name("contributor")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["contributor"])
        @oslc_description("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def contributor(self):
            # Start of user code getterInit:contributor
            # End of user code
            return self._contributor
    
        @contributor.setter
        def contributor(self, value: Set[Link]):
            # Start of user code setterInit:contributor
            # End of user code
            self._contributor = value
            # Start of user code setterFinalize:contributor
            # End of user code
    
        @property
        # Start of user code getterAnnotation:created
        # End of user code
        @oslc_name("created")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["created"])
        @oslc_description("Timestamp of resource creation")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def created(self):
            # Start of user code getterInit:created
            # End of user code
            return self._created
    
        @created.setter
        def created(self, value: datetime):
            # Start of user code setterInit:created
            # End of user code
            self._created = value
            # Start of user code setterFinalize:created
            # End of user code
    
        @property
        # Start of user code getterAnnotation:creator
        # End of user code
        @oslc_name("creator")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["creator"])
        @oslc_description("Creator or creators of the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def creator(self):
            # Start of user code getterInit:creator
            # End of user code
            return self._creator
    
        @creator.setter
        def creator(self, value: Set[Link]):
            # Start of user code setterInit:creator
            # End of user code
            self._creator = value
            # Start of user code setterFinalize:creator
            # End of user code
    
        @property
        # Start of user code getterAnnotation:identifier
        # End of user code
        @oslc_name("identifier")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["identifier"])
        @oslc_description("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def identifier(self):
            # Start of user code getterInit:identifier
            # End of user code
            return self._identifier
    
        @identifier.setter
        def identifier(self, value: str):
            # Start of user code setterInit:identifier
            # End of user code
            self._identifier = value
            # Start of user code setterFinalize:identifier
            # End of user code
    
        @property
        # Start of user code getterAnnotation:modified
        # End of user code
        @oslc_name("modified")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["modified"])
        @oslc_description("Timestamp of latest resource modification")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def modified(self):
            # Start of user code getterInit:modified
            # End of user code
            return self._modified
    
        @modified.setter
        def modified(self, value: datetime):
            # Start of user code setterInit:modified
            # End of user code
            self._modified = value
            # Start of user code setterFinalize:modified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:type
        # End of user code
        @oslc_name("type")
        @oslc_property_definition(rdf_vocabulary_constants.NS_RDF["type"])
        @oslc_description("The resource type URIs")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def type(self):
            # Start of user code getterInit:type
            # End of user code
            return self._type
    
        @type.setter
        def type(self, value: Set[Link]):
            # Start of user code setterInit:type
            # End of user code
            self._type = value
            # Start of user code setterFinalize:type
            # End of user code
    
        @property
        # Start of user code getterAnnotation:instance_shape
        # End of user code
        @oslc_name("instanceShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["instanceShape"])
        @oslc_description("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def instance_shape(self):
            # Start of user code getterInit:instance_shape
            # End of user code
            return self._instance_shape
    
        @instance_shape.setter
        def instance_shape(self, value: Set[Link]):
            # Start of user code setterInit:instance_shape
            # End of user code
            self._instance_shape = value
            # Start of user code setterFinalize:instance_shape
            # End of user code
    
        @property
        # Start of user code getterAnnotation:service_provider
        # End of user code
        @oslc_name("serviceProvider")
        @oslc_property_definition(oslc_constants.NS_OSLC["serviceProvider"])
        @oslc_description("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def service_provider(self):
            # Start of user code getterInit:service_provider
            # End of user code
            return self._service_provider
    
        @service_provider.setter
        def service_provider(self, value: Set[Link]):
            # Start of user code setterInit:service_provider
            # End of user code
            self._service_provider = value
            # Start of user code setterFinalize:service_provider
            # End of user code
    
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:blocked_by_change_request
        # End of user code
        @oslc_name("blockedByChangeRequest")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["blockedByChangeRequest"])
        @oslc_description("Change Request that prevents execution of the Test Execution Record. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[CHANGEREQUEST_TYPE])
        @oslc_read_only(False)
        def blocked_by_change_request(self):
            # Start of user code getterInit:blocked_by_change_request
            # End of user code
            return self._blocked_by_change_request
    
        @blocked_by_change_request.setter
        def blocked_by_change_request(self, value: Set[Link]):
            # Start of user code setterInit:blocked_by_change_request
            # End of user code
            self._blocked_by_change_request = value
            # Start of user code setterFinalize:blocked_by_change_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:related_change_request
        # End of user code
        @oslc_name("relatedChangeRequest")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["relatedChangeRequest"])
        @oslc_description("A related change request. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[CHANGEREQUEST_TYPE])
        @oslc_read_only(False)
        def related_change_request(self):
            # Start of user code getterInit:related_change_request
            # End of user code
            return self._related_change_request
    
        @related_change_request.setter
        def related_change_request(self, value: Set[Link]):
            # Start of user code setterInit:related_change_request
            # End of user code
            self._related_change_request = value
            # Start of user code setterFinalize:related_change_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:reports_on_test_plan
        # End of user code
        @oslc_name("reportsOnTestPlan")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["reportsOnTestPlan"])
        @oslc_description("Test Plan that the Test Execution Record reports on. It is likely that the target resource will be an oslc_qm:TestPlan but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_qm_constants[TESTPLAN_TYPE])
        @oslc_read_only(False)
        def reports_on_test_plan(self):
            # Start of user code getterInit:reports_on_test_plan
            # End of user code
            return self._reports_on_test_plan
    
        @reports_on_test_plan.setter
        def reports_on_test_plan(self, value: Link):
            # Start of user code setterInit:reports_on_test_plan
            # End of user code
            self._reports_on_test_plan = value
            # Start of user code setterFinalize:reports_on_test_plan
            # End of user code
    
        @property
        # Start of user code getterAnnotation:runs_on_test_environment
        # End of user code
        @oslc_name("runsOnTestEnvironment")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["runsOnTestEnvironment"])
        @oslc_description("Indicates the environment details of the test case for this execution record.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def runs_on_test_environment(self):
            # Start of user code getterInit:runs_on_test_environment
            # End of user code
            return self._runs_on_test_environment
    
        @runs_on_test_environment.setter
        def runs_on_test_environment(self, value: Link):
            # Start of user code setterInit:runs_on_test_environment
            # End of user code
            self._runs_on_test_environment = value
            # Start of user code setterFinalize:runs_on_test_environment
            # End of user code
    
        @property
        # Start of user code getterAnnotation:runs_test_case
        # End of user code
        @oslc_name("runsTestCase")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["runsTestCase"])
        @oslc_description("Test Case run by the Test Execution Record. It is likely that the target resource will be an oslc_qm:TestCase but that is not necessarily the case.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_qm_constants[TESTCASE_TYPE])
        @oslc_read_only(False)
        def runs_test_case(self):
            # Start of user code getterInit:runs_test_case
            # End of user code
            return self._runs_test_case
    
        @runs_test_case.setter
        def runs_test_case(self, value: Link):
            # Start of user code setterInit:runs_test_case
            # End of user code
            self._runs_test_case = value
            # Start of user code setterFinalize:runs_test_case
            # End of user code
    
    
