# Start of user code Copyright
#
# Copyright (c) 2020 Contributors to the Eclipse Foundation
#
# See the NOTICE file(s) distributed with this work for additional
# information regarding copyright ownership.
#
# This program and the accompanying materials are made available under the
# terms of the Eclipse Distribution License 1.0 which is available at
# http://www.eclipse.org/org/documents/edl-v10.php.
#
# SPDX-License-Identifier: BSD-3-Simple
#
# This file is generated by Lyo Designer (https://www.eclipse.org/lyo/)
#
# End of user code

from datetime import datetime
from typing import Set
from oslc4py_client.annotation_types.Occurs import Occurs
from oslc4py_client.annotation_types.ValueType import ValueType
from oslc4py_client.OSLCResource import OSLCResource
from oslc4py_client.Link import Link
from oslc4py_client.decorators import oslc_description, oslc_name, oslc_namespace, oslc_occurs, oslc_property_definition, oslc_resource_shape, oslc_value_type, oslc_range, oslc_read_only

from org.eclipse.lyo.oslc.domains.cm.oslc_cm_constants import NS_OSLC_CM
from org.eclipse.lyo.oslc.domains.dcterms_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.foaf_constants import NS_FOAF
from org.eclipse.lyo.oslc4j.core.model.oslc_constants import NS_OSLC
from org.eclipse.lyo.oslc.domains.qm.oslc_qm_constants import NS_OSLC_QM
from org.eclipse.lyo.oslc.domains.rdf_constants import NS_RDF
from org.eclipse.lyo.oslc.domains.rm.oslc_rm_constants import NS_OSLC_RM
from org.eclipse.lyo.oslc.domains.dcterms_vocabulary_constants import NS_DCTERMS
from org.eclipse.lyo.oslc.domains.oslc_qm_vocabulary_constants import NS_OSLC_QM
from org.eclipse.lyo.oslc.domains.rdf_vocabulary_constants import NS_RDF
from org.eclipse.lyo.oslc.domains.cm.ChangeRequest import ChangeRequest
from org.eclipse.lyo.oslc.domains.Person import Person
from org.eclipse.lyo.oslc.domains.rm.Requirement import Requirement
from org.eclipse.lyo.oslc.domains.qm.TestScript import TestScript
# Start of user code imports
# End of user code

# Start of user code preClassCode
# End of user code

# Start of user code classAnnotations
# End of user code
@oslc_namespace(NS_OSLC_QM)
@oslc_name("TestCase")
@oslc_resource_shape(describes=NS_OSLC_QM["TestCase"], title="TestCase Shape")
class TestCase(OSLCResource):
    # Start of user code classAttributes
    # End of user code
    # Start of user code classMethods
    # End of user code
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        # Start of user code constructor
        # End of user code
        # Start of user code attributeAnnotation:contributor
        # End of user code
        self._contributor = set()
        # Start of user code attributeAnnotation:created
        # End of user code
        self._created = None
        # Start of user code attributeAnnotation:creator
        # End of user code
        self._creator = set()
        # Start of user code attributeAnnotation:description
        # End of user code
        self._description = None
        # Start of user code attributeAnnotation:identifier
        # End of user code
        self._identifier = None
        # Start of user code attributeAnnotation:modified
        # End of user code
        self._modified = None
        # Start of user code attributeAnnotation:instance_shape
        # End of user code
        self._instance_shape = set()
        # Start of user code attributeAnnotation:service_provider
        # End of user code
        self._service_provider = set()
        # Start of user code attributeAnnotation:subject
        # End of user code
        self._subject = set()
        # Start of user code attributeAnnotation:title
        # End of user code
        self._title = None
        # Start of user code attributeAnnotation:type
        # End of user code
        self._type = set()
        # Start of user code attributeAnnotation:related_change_request
        # End of user code
        self._related_change_request = set()
        # Start of user code attributeAnnotation:tests_change_request
        # End of user code
        self._tests_change_request = set()
        # Start of user code attributeAnnotation:uses_test_script
        # End of user code
        self._uses_test_script = set()
        # Start of user code attributeAnnotation:validates_requirement
        # End of user code
        self._validates_requirement = set()
        
        @property
        # Start of user code getterAnnotation:contributor
        # End of user code
        @oslc_name("contributor")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["contributor"])
        @oslc_description("Contributor or contributors to the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def contributor(self):
            # Start of user code getterInit:contributor
            # End of user code
            return self._contributor
    
        @contributor.setter
        def contributor(self, value: Set[Link]):
            # Start of user code setterInit:contributor
            # End of user code
            self._contributor = value
            # Start of user code setterFinalize:contributor
            # End of user code
    
        @property
        # Start of user code getterAnnotation:created
        # End of user code
        @oslc_name("created")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["created"])
        @oslc_description("Timestamp of resource creation")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def created(self):
            # Start of user code getterInit:created
            # End of user code
            return self._created
    
        @created.setter
        def created(self, value: datetime):
            # Start of user code setterInit:created
            # End of user code
            self._created = value
            # Start of user code setterFinalize:created
            # End of user code
    
        @property
        # Start of user code getterAnnotation:creator
        # End of user code
        @oslc_name("creator")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["creator"])
        @oslc_description("Creator or creators of the resource. It is likely that the target resource will be a foaf:Person but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(foaf_constants[PERSON_TYPE])
        @oslc_read_only(False)
        def creator(self):
            # Start of user code getterInit:creator
            # End of user code
            return self._creator
    
        @creator.setter
        def creator(self, value: Set[Link]):
            # Start of user code setterInit:creator
            # End of user code
            self._creator = value
            # Start of user code setterFinalize:creator
            # End of user code
    
        @property
        # Start of user code getterAnnotation:description
        # End of user code
        @oslc_name("description")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["description"])
        @oslc_description("Descriptive text about resource represented as rich text in XHTML content. SHOULD include only content that is valid and suitable inside an XHTML <div> element.")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def description(self):
            # Start of user code getterInit:description
            # End of user code
            return self._description
    
        @description.setter
        def description(self, value: str):
            # Start of user code setterInit:description
            # End of user code
            self._description = value
            # Start of user code setterFinalize:description
            # End of user code
    
        @property
        # Start of user code getterAnnotation:identifier
        # End of user code
        @oslc_name("identifier")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["identifier"])
        @oslc_description("A unique identifier for a resource. Typically read-only and assigned by the service provider when a resource is created. Not typically intended for end-user display.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def identifier(self):
            # Start of user code getterInit:identifier
            # End of user code
            return self._identifier
    
        @identifier.setter
        def identifier(self, value: str):
            # Start of user code setterInit:identifier
            # End of user code
            self._identifier = value
            # Start of user code setterFinalize:identifier
            # End of user code
    
        @property
        # Start of user code getterAnnotation:modified
        # End of user code
        @oslc_name("modified")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["modified"])
        @oslc_description("Timestamp of latest resource modification")
        @oslc_occurs(Occurs.ZERO_OR_ONE)
        @oslc_value_type(ValueType.DateTime)
        @oslc_read_only(False)
        def modified(self):
            # Start of user code getterInit:modified
            # End of user code
            return self._modified
    
        @modified.setter
        def modified(self, value: datetime):
            # Start of user code setterInit:modified
            # End of user code
            self._modified = value
            # Start of user code setterFinalize:modified
            # End of user code
    
        @property
        # Start of user code getterAnnotation:instance_shape
        # End of user code
        @oslc_name("instanceShape")
        @oslc_property_definition(oslc_constants.NS_OSLC["instanceShape"])
        @oslc_description("The URI of a Resource Shape that describes the possible properties, occurrence, value types, allowed values and labels. This shape information is useful in displaying the subject resource as well as guiding clients in performing modifications. Instance shapes may be specific to the authenticated user associated with the request that retrieved the resource, the current state of the resource and other factors and thus should not be cached.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def instance_shape(self):
            # Start of user code getterInit:instance_shape
            # End of user code
            return self._instance_shape
    
        @instance_shape.setter
        def instance_shape(self, value: Set[Link]):
            # Start of user code setterInit:instance_shape
            # End of user code
            self._instance_shape = value
            # Start of user code setterFinalize:instance_shape
            # End of user code
    
        @property
        # Start of user code getterAnnotation:service_provider
        # End of user code
        @oslc_name("serviceProvider")
        @oslc_property_definition(oslc_constants.NS_OSLC["serviceProvider"])
        @oslc_description("A link to the resource's OSLC Service Provider. There may be cases when the subject resource is available from a service provider that implements multiple domain specifications, which could result in multiple values for this property.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def service_provider(self):
            # Start of user code getterInit:service_provider
            # End of user code
            return self._service_provider
    
        @service_provider.setter
        def service_provider(self, value: Set[Link]):
            # Start of user code setterInit:service_provider
            # End of user code
            self._service_provider = value
            # Start of user code setterFinalize:service_provider
            # End of user code
    
        @property
        # Start of user code getterAnnotation:subject
        # End of user code
        @oslc_name("subject")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["subject"])
        @oslc_description("Tag or keyword for a resource. Each occurrence of a dcterms:subject property denotes an additional tag for the resource.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.String)
        @oslc_read_only(False)
        def subject(self):
            # Start of user code getterInit:subject
            # End of user code
            return self._subject
    
        @subject.setter
        def subject(self, value: Set[str]):
            # Start of user code setterInit:subject
            # End of user code
            self._subject = value
            # Start of user code setterFinalize:subject
            # End of user code
    
        @property
        # Start of user code getterAnnotation:title
        # End of user code
        @oslc_name("title")
        @oslc_property_definition(dcterms_vocabulary_constants.NS_DCTERMS["title"])
        @oslc_description("Title of the resource represented as rich text in XHTML content. SHOULD include only content that is valid inside an XHTML <span> element.")
        @oslc_occurs(Occurs.EXACTLY_ONE)
        @oslc_value_type("XMLLiteral")
        @oslc_read_only(False)
        def title(self):
            # Start of user code getterInit:title
            # End of user code
            return self._title
    
        @title.setter
        def title(self, value: str):
            # Start of user code setterInit:title
            # End of user code
            self._title = value
            # Start of user code setterFinalize:title
            # End of user code
    
        @property
        # Start of user code getterAnnotation:type
        # End of user code
        @oslc_name("type")
        @oslc_property_definition(rdf_vocabulary_constants.NS_RDF["type"])
        @oslc_description("The resource type URIs")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_read_only(False)
        def type(self):
            # Start of user code getterInit:type
            # End of user code
            return self._type
    
        @type.setter
        def type(self, value: Set[Link]):
            # Start of user code setterInit:type
            # End of user code
            self._type = value
            # Start of user code setterFinalize:type
            # End of user code
    
        @property
        # Start of user code getterAnnotation:related_change_request
        # End of user code
        @oslc_name("relatedChangeRequest")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["relatedChangeRequest"])
        @oslc_description("A related change request. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[CHANGEREQUEST_TYPE])
        @oslc_read_only(False)
        def related_change_request(self):
            # Start of user code getterInit:related_change_request
            # End of user code
            return self._related_change_request
    
        @related_change_request.setter
        def related_change_request(self, value: Set[Link]):
            # Start of user code setterInit:related_change_request
            # End of user code
            self._related_change_request = value
            # Start of user code setterFinalize:related_change_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:tests_change_request
        # End of user code
        @oslc_name("testsChangeRequest")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["testsChangeRequest"])
        @oslc_description("Change Request tested by the Test Case. It is likely that the target resource will be an oslc_cm:ChangeRequest but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_cm_constants[CHANGEREQUEST_TYPE])
        @oslc_read_only(False)
        def tests_change_request(self):
            # Start of user code getterInit:tests_change_request
            # End of user code
            return self._tests_change_request
    
        @tests_change_request.setter
        def tests_change_request(self, value: Set[Link]):
            # Start of user code setterInit:tests_change_request
            # End of user code
            self._tests_change_request = value
            # Start of user code setterFinalize:tests_change_request
            # End of user code
    
        @property
        # Start of user code getterAnnotation:uses_test_script
        # End of user code
        @oslc_name("usesTestScript")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["usesTestScript"])
        @oslc_description("Test Script used by the Test Case. It is likely that the target resource will be an oslc_qm:TestScript but that is not necessarily the case.")
        @oslc_occurs(Occurs.ONE_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_qm_constants[TESTSCRIPT_TYPE])
        @oslc_read_only(False)
        def uses_test_script(self):
            # Start of user code getterInit:uses_test_script
            # End of user code
            return self._uses_test_script
    
        @uses_test_script.setter
        def uses_test_script(self, value: Set[Link]):
            # Start of user code setterInit:uses_test_script
            # End of user code
            self._uses_test_script = value
            # Start of user code setterFinalize:uses_test_script
            # End of user code
    
        @property
        # Start of user code getterAnnotation:validates_requirement
        # End of user code
        @oslc_name("validatesRequirement")
        @oslc_property_definition(oslc_qm_vocabulary_constants.NS_OSLC_QM["validatesRequirement"])
        @oslc_description("Requirement that is validated by the Test Case. It is likely that the target resource will be an oslc_rm:Requirement but that is not necessarily the case.")
        @oslc_occurs(Occurs.ZERO_OR_MANY)
        @oslc_value_type(ValueType.Resource)
        @oslc_range(oslc_rm_constants[REQUIREMENT_TYPE])
        @oslc_read_only(False)
        def validates_requirement(self):
            # Start of user code getterInit:validates_requirement
            # End of user code
            return self._validates_requirement
    
        @validates_requirement.setter
        def validates_requirement(self, value: Set[Link]):
            # Start of user code setterInit:validates_requirement
            # End of user code
            self._validates_requirement = value
            # Start of user code setterFinalize:validates_requirement
            # End of user code
    
    
